### ISSUE TITLE
Testing the model with our own audio sample gives size mismatch tensor errors

### ISSUE THREAD

**Issue by TejasNaikk** [luckytoilet/kaggle-speech-recognition#1]
Hi. I trained the model for speech recognition. But while testing with my own audio clip of 1 second i get the following error:

Traceback (most recent call last):
  File "testing.py", line 57, in <module>
    for f, data in test_loader:
  File "/home/conex/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/conex/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/conex/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/conex/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/conex/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/conex/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 115, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 481 and 161 in dimension 2 at /opt/conda/conda-bld/pytorch_1524590031827/work/aten/src/TH/generic/THTensorMath.c:3586

Could you please tell me what should I modify to get generalized audio clips to test

**Comment by lucky-bai** [comment]
Looks like the data is not in the right format. What's `testing.py`?

**Comment by TejasNaikk** [comment]
That's predict.py.. I just named it to testing.py .. the data is a .Wav audio of 1 second recorded from my laptop.. I am trying to predict using my trained model on that audio

**Comment by lucky-bai** [comment]
I don't remember how to run this -- but I remember that the WAV file has to be a specific format (mono at a specific bitrate). Try getting it working with the Kaggle dataset first?

**Comment by TejasNaikk** [comment]
Yeaa I tried with the kaggle dataset. It is working with that.. I just want to use the model for real time word recognition. So for my own audios how do I do it?
